const fs = require('fs');
const d = JSON.parse(fs.readFileSync('src/data/player-names.json', 'utf8'));

const map = {
  // Brazil
  'Alisson': '阿利松',
  'Éderson Silva': '埃德森',
  'Gabriel Magalhães': '加布里埃尔',
  'Marquinhos': '马尔基尼奥斯',
  'Casemiro': '卡塞米罗',
  'Alex Sandro': '阿莱士·桑德罗',
  'Vinícius Júnior': '维尼修斯',
  'Bruno Guimarães': '吉马良斯',
  'Matheus Cunha': '库尼亚',
  'Neymar': '内马尔',
  'Raphinha': '拉菲尼亚',
  'Weverton': '韦弗顿',
  'Danilo Luiz': '达尼洛',
  'Bremer': '布雷默',
  'Léo Pereira': '莱奥·佩雷拉',
  'Douglas Santos': '道格拉斯·桑托斯',
  'Fabinho': '法比尼奥',
  'Danilo Santos': '达尼洛',
  'Endrick': '恩德里克',
  'Lucas Paquetá': '帕奎塔',
  'Luiz Henrique': '路易斯·恩里克',
  'Gabriel Martinelli': '马丁内利',
  'Ederson Moraes': '埃德森',
  'Roger Ibañez': '伊巴涅斯',
  'Igor Thiago': '伊戈尔·蒂亚戈',
  'Rayan': '拉扬',
  // Haiti
  'Johny Placide': '普拉西德',
  'Carlens Arcus': '阿尔库斯',
  'Keeto Thermoncy': '泰尔蒙西',
  'Ricardo Adé': '阿德',
  'Hannes Delcroix': '德尔克鲁瓦',
  'Carl Sainté': '桑泰',
  'Derrick Etienne Jr.': '艾蒂安',
  'Martin Expérience': '埃斯佩里扬斯',
  'Duckens Nazon': '纳宗',
  'Jean-Ricner Bellegarde': '贝勒加德',
  'Louicius Deedson': '德德松',
  'Alexandre Pierre': '皮埃尔',
  'Duke Lacroix': '拉克鲁瓦',
  'Garven Metusala': '梅图萨拉',
  'Ruben Providence': '普罗维登斯',
  'Lenny Joseph': '约瑟夫',
  'Danley Jean Jacques': '让-雅克',
  'Wilson Isidor': '伊西多尔',
  'Yassin Fortuné': '福蒂内',
  'Frantzdy Pierrot': '皮埃罗',
  'Josué Casimir': '卡西米尔',
  'Jean-Kévin Duverne': '迪韦尔纳',
  'Josué Duverger': '迪韦尔热',
  'Wilguens Paugain': '波甘',
  'Dominique Simon': '西蒙',
  'Woodensky Pierre': '皮埃尔',
  // Morocco
  'Yassine Bounou': '布努',
  'Achraf Hakimi': '阿什拉夫',
  'Noussair Mazraoui': '马兹拉维',
  'Sofyan Amrabat': '阿姆拉巴特',
  'Marwane Saâdane': '萨达内',
  'Ayyoub Bouaddi': '布阿迪',
  'Chemsdine Talbi': '塔尔比',
  'Azzedine Ounahi': '奥纳希',
  'Soufiane Rahimi': '拉希米',
  'Brahim Díaz': '卜拉欣·迪亚斯',
  'Ismael Saibari': '赛巴里',
  'Munir Mohamedi': '穆尼尔',
  'Zakaria El Ouahdi': '埃尔瓦赫迪',
  'Issa Diop': '迪奥普',
  'Samir El Mourabet': '穆拉贝特',
  'Gessime Yassine': '亚辛',
  'Amine Sbaï': '斯巴伊',
  'Chadi Riad': '里亚德',
  'Youssef Belammari': '贝拉马里',
  'Ayoub El Kaabi': '埃尔卡比',
  'Ayoube Amaimouni': '阿伊穆尼',
  'Ahmed Reda Tagnaouti': '塔格瑙提',
  'Bilal El Khannouss': '汉努斯',
  'Neil El Aynaoui': '艾纳维',
  'Redouane Halhal': '勒哈勒',
  'Anass Salah-Eddine': '萨拉赫-丁',
  // Scotland
  'Angus Gunn': '冈恩',
  'Aaron Hickey': '希基',
  'Andy Robertson': '罗伯逊',
  'Scott McTominay': '麦克托米奈',
  'Grant Hanley': '汉利',
  'Kieran Tierney': '蒂尔尼',
  'John McGinn': '麦金',
  'Tyler Fletcher': '弗莱彻',
  'Lyndon Dykes': '戴克斯',
  'Ché Adams': '亚当斯',
  'Ryan Christie': '克里斯蒂',
  'Liam Kelly': '凯利',
  'Jack Hendry': '亨德里',
  'Ross Stewart': '斯图尔特',
  'John Souttar': '苏塔',
  'Dominic Hyam': '海厄姆',
  'Ben Gannon-Doak': '多克',
  'George Hirst': '赫斯特',
  'Lewis Ferguson': '弗格森',
  'Lawrence Shankland': '尚克兰',
  'Craig Gordon': '戈登',
  'Nathan Patterson': '帕特森',
  'Kenny McLean': '麦克莱恩',
  'Anthony Ralston': '罗尔斯顿',
  'Findlay Curtis': '柯蒂斯',
  'Scott McKenna': '麦肯纳'
};

Object.assign(d, map);
fs.writeFileSync('src/data/player-names.json', JSON.stringify(d, null, 2), 'utf8');
console.log('Done. Updated 104 names (4 teams).');
